[versions]
minSdk = "23"
targetSdk = "33"
compileSdk = "33"
versionCode = "1"
versionName = "1.0"

[libraries]
kiwi-icons = "kiwi.orbit.compose:icons:0.18.0"
kiwi-ui = "kiwi.orbit.compose:ui:0.18.0"
kiwi-illustrations = "kiwi.orbit.compose:illustrations:0.18.0"
androidx-compose-navigation = "androidx.navigation:navigation-compose:2.5.1"
androidx-compose-foundation = "androidx.compose.foundation:foundation:1.3.0-beta01"
androidx-compose-ui = "androidx.compose.ui:ui:1.3.0-alpha01"
androidx-compose-material = "androidx.compose.material:material:1.3.0-beta01"
androidx-compose-tooling-preview = "androidx.compose.ui:ui-tooling-preview:1.3.0-alpha01"
androidx-compose-tooling-poolingcontainer = "androidx.customview:customview-poolingcontainer:1.0.0"
androidx-compose-tooling = "androidx.compose.ui:ui-tooling:1.1.1"
androidx-lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"
androidx-compose-activity = "androidx.activity:activity-compose:1.5.1"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-datastore-core = "androidx.datastore:datastore-core:1.0.0"
androidx-datastore = "androidx.datastore:datastore:1.0.0"
androidx-test-coreKtx = "androidx.test:core-ktx:1.4.0"
androidx-test-core = "androidx.test:core:1.4.0"
androidx-test-core-junitKtx = "androidx.test.ext:junit-ktx:1.1.3"
androidx-test-runner = "androidx.test:runner:1.4.0"
androidx-test-rules = "androidx.test:rules:1.4.0"
androidx-core = "androidx.core:core-ktx:1.8.0"
androidx-room-runtime = "androidx.room:room-runtime:2.4.2"
androidx-room-ktx = "androidx.room:room-runtime:2.4.2"
androidx-room-compiler = "androidx.room:room-runtime:2.4.2"
accompanist = "com.google.accompanist:accompanist-systemuicontroller:0.24.8-beta"
mockk = "io.mockk:mockk:1.12.5"
mockk-android = "io.mockk:mockk-android:1.12.5"
junit = "junit:junit:4.13.2"
robolectric = "org.robolectric:robolectric:4.8.2"
coil = "io.coil-kt:coil-compose:2.1.0"
firebase-crashlytics = "com.google.firebase:firebase-crashlytics:18.2.9"
firebase-analytics = "com.google.firebase:firebase-crashlytics:18.2.9"


[bundles]
kiwi = ["kiwi-icons", "kiwi-ui", "kiwi-illustrations"]
androidx-room = ["androidx-room-runtime", "androidx-room-ktx"]
firebase = ["firebase-crashlytics", "firebase-analytics"]
androidx-androidTests = ["androidx-test-coreKtx", "androidx-test-runner", "androidx-test-rules", "androidx-test-core-junitKtx"]
androidx-compose = ["androidx-compose-foundation", "accompanist", "androidx-compose-tooling-preview", "androidx-compose-ui", "androidx-compose-material", "androidx-compose-activity", ]
androidx-compose-tooling = ["androidx-compose-tooling-poolingcontainer", "androidx-compose-tooling"]